zuul:
  # 忽略所有项目服务的敏感头信息（注入）
  sensitive-headers: 
  routes:
    # 自定义路由的地址
    product-server: /myProduct/**
    order-server: /myOrder/**
  # 禁止路由的url
  #ignored-patterns:
   # - /**/person/print
spring:
  rabbitmq:
    host: 47.104.211.18
    port: 5672
    username: wholve
    password: wholve

#zuul:
#  routes: 
#    abc:
#      path: /myProduct/**
#      serviceId: product-server
#      # 开放传递cookie
#      sensitiveHeaders:
#management:
#  security:
#    enabled: false
